# Generated by Django 3.1 on 2020-08-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sing', models.CharField(help_text='Название категории в единственном числе', max_length=200)),
                ('name_plur', models.CharField(help_text='Название категории во множественном числе', max_length=200)),
            ],
            options={
                'ordering': ['-name_sing'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/img/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок', max_length=200)),
                ('description', models.CharField(help_text='Описание', max_length=200)),
                ('author', models.CharField(help_text='Автор', max_length=200)),
                ('data', models.TextField(help_text='Текст публикации')),
                ('preview', models.ImageField(upload_to='uploads/previews/%Y/%m/%d')),
                ('date', models.DateTimeField(auto_now=True)),
                ('attached_files', models.ManyToManyField(help_text='прикрепленные файлы', to='seven_op.UploadedFile')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seven_op.category')),
                ('photos_for_spin', models.ManyToManyField(help_text='Фото на "карусель"', to='seven_op.UploadedPhoto')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
