# Generated by Django 3.1 on 2020-08-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attached_files',
            field=models.ManyToManyField(help_text='прикрепленные файлы', null=True, to='seven_op.UploadedFile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photos_for_spin',
            field=models.ManyToManyField(help_text='Фото на "карусель"', null=True, to='seven_op.UploadedPhoto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(null=True, upload_to='uploads/previews/%Y/%m/%d'),
        ),
    ]
