# Generated by Django 3.1 on 2020-08-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0003_auto_20200822_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя автора блогов', max_length=200)),
                ('info', models.TextField(help_text='Информация об автора блогов')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок', max_length=200)),
                ('description', models.CharField(help_text='Описание', max_length=200)),
                ('data', models.TextField(help_text='Текст публикации')),
                ('preview', models.ImageField(default=None, null=True, upload_to='uploads/previews/%Y/%m/%d')),
                ('date', models.DateTimeField(auto_now=True)),
                ('attached_files', models.ManyToManyField(default=None, help_text='прикрепленные файлы', null=True, to='seven_op.UploadedFile')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seven_op.blogauthor')),
                ('photos_for_spin', models.ManyToManyField(default=None, help_text='Фото на "карусель"', null=True, to='seven_op.UploadedPhoto')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
