# Generated by Django 3.1 on 2020-08-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0005_auto_20200822_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='attached_files',
            field=models.ManyToManyField(blank=True, default=None, help_text='прикрепленные файлы', null=True, to='seven_op.UploadedFile'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photos_for_spin',
            field=models.ManyToManyField(blank=True, default=None, help_text='Фото на "карусель"', null=True, to='seven_op.UploadedPhoto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attached_files',
            field=models.ManyToManyField(blank=True, default=None, help_text='прикрепленные файлы', null=True, to='seven_op.UploadedFile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photos_for_spin',
            field=models.ManyToManyField(blank=True, default=None, help_text='Фото на "карусель"', null=True, to='seven_op.UploadedPhoto'),
        ),
    ]
