# Generated by Django 3.1 on 2020-08-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0007_auto_20200823_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Имя автора', max_length=200)),
                ('data', models.TextField(help_text='Текст комментария')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, help_text='Комментарии к блогу', null=True, to='seven_op.Comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, help_text='Комментарии к публикации', null=True, to='seven_op.Comment'),
        ),
    ]
