# Generated by Django 3.1 on 2020-08-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0009_category_name_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seven_op.uploadedphoto'),
        ),
    ]
