# Generated by Django 3.1 on 2020-08-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0010_blogauthor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedphoto',
            name='index',
            field=models.ImageField(default=1, help_text='поставьте 0, если загружаете фото для карусели, и оно должно стоять первым', null=True, upload_to=''),
        ),
    ]
