# Generated by Django 3.1 on 2020-08-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0011_uploadedphoto_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='index',
            field=models.IntegerField(default=1, help_text='поставьте 0, если загружаете фото для карусели, и оно должно стоять первым', null=True),
        ),
    ]
