# Generated by Django 3.1 on 2020-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0012_auto_20200823_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='index',
            field=models.IntegerField(default=1, help_text='если загружаете фото для карусели, то пронумеруйте их с 0', null=True),
        ),
    ]
