# Generated by Django 3.1 on 2020-08-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0013_auto_20200823_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default=1, help_text='название файла', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='name',
            field=models.CharField(default=3, help_text='Название фото', max_length=200),
            preserve_default=False,
        ),
    ]
