# Generated by Django 3.1 on 2020-08-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0014_auto_20200823_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-data']},
        ),
    ]
