# Generated by Django 3.1 on 2020-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0015_auto_20200824_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_plur',
            field=models.CharField(help_text='Название категории во множественном числе', max_length=200, verbose_name='имя во множественном числе'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_sing',
            field=models.CharField(help_text='Название категории в единственном числе', max_length=200, verbose_name='имя в единственном числе'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_url',
            field=models.CharField(help_text='название, которое будет отображаться в ссылках', max_length=200, verbose_name='имя для ссылки'),
        ),
    ]
