# Generated by Django 3.1 on 2020-09-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0016_auto_20200909_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='info',
            field=models.TextField(help_text='необязательное поле', null=True, verbose_name='информация об авторе'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='имя автора блогов'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='выберете фото из загруженных', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seven_op.uploadedphoto'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_plur',
            field=models.CharField(max_length=200, verbose_name='имя во множественном числе'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_sing',
            field=models.CharField(max_length=200, verbose_name='имя в единственном числе'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_url',
            field=models.CharField(max_length=200, verbose_name='имя для ссылки'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=200, verbose_name='имя автора'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.TextField(verbose_name='текст комментария'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/files/%Y/%m/%d', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='имя файла'),
        ),
        migrations.AlterField(
            model_name='uploadedphoto',
            name='index',
            field=models.IntegerField(default=1, help_text='если загружаете фото для карусели, то пронумеруйте их с 0', null=True, verbose_name='номер фото в карусели'),
        ),
        migrations.AlterField(
            model_name='uploadedphoto',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название фото'),
        ),
        migrations.AlterField(
            model_name='uploadedphoto',
            name='photo',
            field=models.ImageField(upload_to='uploads/img/%Y/%m/%d', verbose_name='фото'),
        ),
    ]
