# Generated by Django 3.1 on 2020-09-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0018_auto_20200909_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='attached_files',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='seven_op.UploadedFile', verbose_name='прикрепленные файлы'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='seven_op.Comment', verbose_name='Комментарии к блогу'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='data',
            field=models.TextField(verbose_name='текст блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photos_for_spin',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='seven_op.UploadedPhoto', verbose_name='Фото на "карусель"'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(default=None, null=True, upload_to='uploads/previews/%Y/%m/%d', verbose_name='фото на заголовок'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attached_files',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='seven_op.UploadedFile', verbose_name='прикрепленные файлы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200, verbose_name='имя автора'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='seven_op.Comment', verbose_name='комментарии к публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.TextField(verbose_name='текст публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='необязательное поле', max_length=200, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photos_for_spin',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='seven_op.UploadedPhoto', verbose_name='фото на "карусель"'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/previews/%Y/%m/%d', verbose_name='фото на заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
    ]
