# Generated by Django 3.1 on 2020-09-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0019_auto_20200909_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name_sing'], 'verbose_name_plural': 'Категории'},
        ),
    ]
