# Generated by Django 3.1 on 2020-09-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0020_auto_20200909_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Авторы блогов'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name_plural': 'Загруженные файлы'},
        ),
        migrations.AlterModelOptions(
            name='uploadedphoto',
            options={'verbose_name_plural': 'Загруженные фото'},
        ),
    ]
