# Generated by Django 3.1 on 2020-09-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0022_auto_20200909_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(default=None, null=True, upload_to='seven_op/static/uploads/previews/%Y/%m/%d', verbose_name='фото на заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='seven_op/static/uploads/previews/%Y/%m/%d', verbose_name='фото на заголовок'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='seven_op/static/uploads/files/%Y/%m/%d', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='uploadedphoto',
            name='photo',
            field=models.ImageField(upload_to='seven_op/static/uploads/img/%Y/%m/%d', verbose_name='фото'),
        ),
    ]
