# Generated by Django 3.1 on 2020-09-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0023_auto_20200924_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='attached_files',
            field=models.ManyToManyField(blank=True, default=None, to='seven_op.UploadedFile', verbose_name='прикрепленные файлы'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, to='seven_op.Comment', verbose_name='Комментарии к блогу'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photos_for_spin',
            field=models.ManyToManyField(blank=True, default=None, to='seven_op.UploadedPhoto', verbose_name='Фото на "карусель"'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attached_files',
            field=models.ManyToManyField(blank=True, default=None, to='seven_op.UploadedFile', verbose_name='прикрепленные файлы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, to='seven_op.Comment', verbose_name='комментарии к публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photos_for_spin',
            field=models.ManyToManyField(blank=True, default=None, to='seven_op.UploadedPhoto', verbose_name='фото на "карусель"'),
        ),
    ]
