# Generated by Django 3.1 on 2020-09-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_op', '0024_auto_20200924_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_title', models.CharField(max_length=200, verbose_name='заголовок параграфа')),
                ('paragraph_img', models.ImageField(upload_to='seven_op/static/uploads/files/%Y/%m/%d', verbose_name='фото к параграфу')),
                ('paragraph_text', models.TextField(verbose_name='текст параграфа')),
                ('is_strong', models.BooleanField(verbose_name='жирный текст')),
                ('paragraph_nb', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Параграфы',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='data',
        ),
        migrations.RemoveField(
            model_name='post',
            name='data',
        ),
        migrations.AddField(
            model_name='blog',
            name='paragraphs',
            field=models.ManyToManyField(to='seven_op.Paragraph', verbose_name='Параграфы'),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraphs',
            field=models.ManyToManyField(to='seven_op.Paragraph', verbose_name='Параграфы'),
        ),
    ]
